---
name: Bug
description: "File a bug report, if you've discovered a problem in Skybrud Redirects."
labels: "type/bug"
body:
- type: input
  id: "version"
  attributes:
    label: "Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)"
  validations:
    required: true
- type: input
  id: "umbracoVersion"
  attributes:
    label: "Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)"
    description: "Use the help icon in the Umbraco backoffice to find the version you're using."
  validations:
    required: true
- type: textarea
  id: "description"
  attributes:
    label: "Bug description"
    description: "Describe the bug."
    placeholder: >
      Try to pinpoint it as much as possible.
      
      Try to state the actual problem, and not just what you think the solution might be.
  validations:
    required: true
